### ISSUE TITLE
Error when call removeAllRow and call addRow

### ISSUE THREAD

**Issue by adarmawan117** [DJ-Raven/jtable-custom#2]
I facing some error when call removeAllRow() (clear all record), and call addRow() (to update record).
This is my code:

```
public void set(String query, Table tabel, String[] listField) {

        int countField = listField.length;
        try {
            ResultSet rs = connect.executeQuery(query); // database ResultSet

            Object[] listObjek = new Object[countField];
            tabel.removeAllRows();                            // clear all row
            while (rs.next()) {
                for (int i = 0; i < countField ; i++) {
                    listObjek[i] = rs.getString(listField[i]);
                }
                tabel.addRow(new PengembalianModel(listObjek), false);    // here is the error.
            }

        } catch (SQLException ex) {
            
        }

    }
```

I Think the error is here:
```
public void stopCellEditing() {
    if (isEditing()) {
        getCellEditor().stopCellEditing();
    }
}
```
In TableCustom.java

**Comment by adarmawan117** [comment]
This my exception
```
run:
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at java.util.Vector.elementAt(Vector.java:479)
	at javax.swing.table.DefaultTableModel.setValueAt(DefaultTableModel.java:664)
	at javax.swing.JTable.setValueAt(JTable.java:2744)
	at javax.swing.JTable.editingStopped(JTable.java:4729)
	at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141)
	at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:368)
	at javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:233)
	at com.raven.table.TableCustom.stopCellEditing(TableCustom.java:310)
	at com.raven.table.TableCustom.addRow(TableCustom.java:245)
	at method.table.SetTableImpl.set(SetTableImpl.java:78)   // here when i call addRow()

// Don't think about the code below

	at controller.PengembalianController.setTable(PengembalianController.java:41)
	at view.PanelPengembalian.reset(PanelPengembalian.java:98)
	at view.PanelPengembalian.accept(PanelPengembalian.java:38)
	at view.PanelPengembalian.access$000(PanelPengembalian.java:12)
	at view.PanelPengembalian$1.actionPerformed(PanelPengembalian.java:81)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at javax.swing.plaf.basic.BasicTableUI$Handler.repostEvent(BasicTableUI.java:948)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1164)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by adarmawan117** [comment]
I have solved this problem. I change stopCellEditing() method to this :

```
    public void stopCellEditing() {
        if (datas.isEmpty()) {
            return;
        }

        if (isEditing()) {
            getCellEditor().stopCellEditing();
        }
    }
```
